import { Village, Stay, Activity, CommunityPost, TravelGroup, Host, Review } from '../types';

export const mockVillages: Village[] = [
  {
    id: '1',
    name: 'Grindelwald',
    location: 'Swiss Alps',
    country: 'Switzerland',
    description: 'Traditional Alpine village nestled beneath the Eiger North Face. Experience cheese-making, hiking, and mountain culture.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3',
    rating: 4.9,
    reviewCount: 234,
    priceFrom: 85,
    currency: 'CHF',
    tags: ['Mountain', 'Alpine', 'Hiking'],
    featured: true,
  },
  {
    id: '2',
    name: 'Positano',
    location: 'Amalfi Coast',
    country: 'Italy',
    description: 'Picturesque cliffside village known for its cascading lemon groves and traditional ceramics workshops.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?ixlib=rb-4.0.3',
    rating: 4.7,
    reviewCount: 189,
    priceFrom: 125,
    currency: 'EUR',
    tags: ['Coastal', 'Mediterranean', 'Crafts'],
    featured: true,
  },
  {
    id: '3',
    name: 'Shirakawa-go',
    location: 'Gifu Prefecture',
    country: 'Japan',
    description: 'Historic village famous for traditional gassho-zukuri farmhouses with steep thatched roofs.',
    image: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?ixlib=rb-4.0.3',
    rating: 4.8,
    reviewCount: 156,
    priceFrom: 95,
    currency: 'JPY',
    tags: ['Historic', 'Traditional', 'UNESCO'],
    featured: true,
  },
];

export const mockStays: Stay[] = [
  {
    id: '1',
    name: 'Casa Maria - Family Farm',
    type: 'homestay',
    location: 'Tuscany',
    country: 'Italy',
    description: 'Traditional farmhouse stay with organic garden, cooking classes, and wine tasting. Family has been farming here for 4 generations.',
    images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3'],
    rating: 4.9,
    reviewCount: 127,
    pricePerNight: 89,
    currency: 'EUR',
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Kitchen', 'Garden', 'Parking'],
    host: {
      name: 'Maria & Giuseppe',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3',
      verified: true,
      responseRate: 98,
    },
    features: ['Organic Farm', 'Cooking Classes', 'Wine Tasting'],
  },
  {
    id: '2',
    name: 'Alpine Green Lodge',
    type: 'eco-lodge',
    location: 'Grindelwald',
    country: 'Switzerland',
    description: 'Sustainable mountain lodge with solar power, local materials, and guided hiking. Perfect for nature lovers seeking authentic Alpine experience.',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3'],
    rating: 4.8,
    reviewCount: 89,
    pricePerNight: 145,
    currency: 'CHF',
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Solar Power', 'Hiking Guides', 'Mountain Views'],
    host: {
      name: 'Klaus',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3',
      verified: true,
      responseRate: 95,
    },
    features: ['Eco-friendly', 'Mountain Views', 'Guided Hiking'],
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    name: 'Traditional Pottery Making',
    category: 'workshop',
    location: 'Monsaraz',
    country: 'Portugal',
    description: 'Learn ancient Portuguese pottery techniques passed down through generations. Create your own ceramic piece to take home.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3',
    rating: 4.9,
    reviewCount: 89,
    price: 45,
    currency: 'EUR',
    duration: '3 hours',
    maxParticipants: 8,
    included: ['Materials', 'Tools', 'Firing', 'Refreshments'],
    difficulty: 'easy',
  },
  {
    id: '2',
    name: 'Nonna\'s Cooking Class',
    category: 'food',
    location: 'Tuscany',
    country: 'Italy',
    description: 'Cook traditional Tuscan dishes using family recipes. Includes market visit, cooking session, and shared meal with the family.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3',
    rating: 4.8,
    reviewCount: 127,
    price: 75,
    currency: 'EUR',
    duration: '4 hours',
    maxParticipants: 6,
    included: ['Market Tour', 'Ingredients', 'Meal', 'Recipes'],
    difficulty: 'easy',
  },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: '1',
    author: {
      name: 'Michael Chen',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3',
      badge: 'Village Explorer',
    },
    title: 'Best cooking classes in Tuscan villages?',
    content: 'I\'m planning a trip to Tuscany next month and would love to take authentic cooking classes with local families. Has anyone had amazing experiences they\'d recommend?',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3',
    location: 'Tuscany, Italy',
    tags: ['Cooking', 'Tuscany', 'Food'],
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    likes: 24,
    comments: 7,
    shares: 3,
  },
  {
    id: '2',
    author: {
      name: 'Elena Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3',
    },
    title: 'Just completed the most amazing rice terraces trek!',
    content: 'Spent 3 days hiking through the Sapa rice terraces with local H\'mong guides. The hospitality was incredible - they invited me to help with planting and taught me traditional weaving.',
    location: 'Sapa, Vietnam',
    tags: ['Hiking', 'Vietnam', 'Culture'],
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    likes: 42,
    comments: 12,
    shares: 8,
  },
];

export const mockTravelGroups: TravelGroup[] = [
  {
    id: '1',
    name: 'Alpine Village Explorers',
    description: 'Dedicated to exploring authentic mountain villages across Europe. Join us for guided tours, cultural exchanges, and alpine adventures.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3',
    memberCount: 1234,
    category: 'Adventure',
    privacy: 'public',
    recentActivity: '12 events this month',
    tags: ['Mountains', 'Europe', 'Adventure'],
    icon: 'mountain',
  },
  {
    id: '2',
    name: 'Village Food Experiences',
    description: 'Discover authentic village cuisines, traditional cooking methods, and food festivals. Perfect for culinary enthusiasts and food photographers.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3',
    memberCount: 2156,
    category: 'Food',
    privacy: 'public',
    recentActivity: '28 events this month',
    tags: ['Food', 'Cooking', 'Culture'],
    icon: 'utensils',
  },
];

export const mockHosts: Host[] = [
  {
    id: '1',
    name: 'Maria Rossi',
    location: 'Tuscany',
    country: 'Italy',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3',
    rating: 4.9,
    reviewCount: 127,
    verified: true,
    superhost: true,
    yearStarted: 2019,
    totalGuests: 450,
    description: 'Third-generation farmer offering authentic Tuscan farm experiences. Specializes in traditional cooking, wine-making, and organic farming practices.',
    specialties: ['Cooking', 'Wine Making', 'Organic Farming'],
    languages: ['Italian', 'English', 'French'],
    responseTime: 'Within an hour',
  },
  {
    id: '2',
    name: 'Pemba Sherpa',
    location: 'Annapurna Region',
    country: 'Nepal',
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?ixlib=rb-4.0.3',
    rating: 4.8,
    reviewCount: 89,
    verified: true,
    superhost: false,
    yearStarted: 2020,
    totalGuests: 280,
    description: 'Experienced mountain guide and eco-lodge owner. Offers trekking adventures and insights into Sherpa culture and Buddhist traditions.',
    specialties: ['Trekking', 'Mountain Guiding', 'Buddhist Culture'],
    languages: ['Nepali', 'English', 'Tibetan'],
    responseTime: 'Within a few hours',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    author: {
      name: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3',
      verified: true,
    },
    rating: 5,
    title: 'Unforgettable Experience at Maria\'s Traditional Farm',
    content: 'My stay at Maria\'s farm in Tuscany exceeded all expectations. From the moment I arrived, I felt like part of the family. Maria taught me how to make fresh pasta from scratch, and we spent hours in the kitchen sharing stories about her grandmother\'s recipes.',
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3'],
    location: 'Tuscany, Italy',
    date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    helpful: 23,
    type: 'stay',
    targetId: '1',
  },
  {
    id: '2',
    author: {
      name: 'James Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3',
      verified: true,
    },
    rating: 4.5,
    title: 'Amazing Pottery Workshop in Oaxaca',
    content: 'The ceramic pottery workshop with master artisan Carlos was incredible. He has been working with clay for over 40 years and his expertise really shows. We learned traditional Zapotec techniques that have been passed down through generations.',
    location: 'Oaxaca, Mexico',
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    helpful: 18,
    type: 'activity',
    targetId: '1',
  },
];
